apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
spec:
  replicas: 6
  selector:
    matchLabels:
      papa: pushpa
  template:
    metadata:
      name: redtheme-pod
      labels:
        papa: pushpa
    spec:
      containers:
        - name: myapp
          image: monikasri237/deployment:red
          ports:
            - containerPort: 80
